export const SET_ALERT = 'SET_ALERT'
export const REMOVE_ALERT = 'REMOVE_ALERT'

export const SAVE_NFT_DETAILS_REQUEST = 'SAVE_NFT_DETAILS_REQUEST'
export const SAVE_NFT_DETAILS_SUCCESS = 'SAVE_NFT_DETAILS_SUCCESS'
export const SAVE_NFT_DETAILS_FAIL = 'SAVE_NFT_DETAILS_FAIL'

export const NFT_DETAILS_REQUEST = 'NFT_DETAILS_REQUEST'
export const NFT_DETAILS_SUCCESS = 'NFT_DETAILS_SUCCESS'
export const NFT_DETAILS_FAIL = 'NFT_DETAILS_FAIL'
export const NFT_DETAILS_RESET = 'NFT_DETAILS_RESET'

export const USER_UPDATE_NFT_SUCCESS = 'USER_UPDATE_NFT_SUCCESS'
export const USER_UPDATE_NFT_REQUEST = 'USER_UPDATE_NFT_REQUEST'
export const USER_UPDATE_NFT_FAIL = 'USER_UPDATE_NFT_FAIL'
export const USER_UPDATE_NFT_RESET = 'USER_UPDATE_NFT_RESET'

export const CLEAR_ERRORS = 'CLEAR_ERRORS'